name: Building release for AHK scripts

on: push

jobs:
  AHK:
    name: Building AHK
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ahk2Exe TTS
        uses: YoraiLevi/GitHub-Action-Ahk2Exe@main
        with:
          in: .\TTS\main.ahk
#           out: $PWD\main.exe

      - name: Ahk2Exe BaseRemap
        uses: YoraiLevi/GitHub-Action-Ahk2Exe@main
        with:
          in: .\KeyboardRemap\BaseRemap.ahk
#           out: $PWD\BaseRemap.exe

      - name: Ahk2Exe Vivobook_ASUSLaptop TP412FAC_TP412FA Remap
        uses: YoraiLevi/GitHub-Action-Ahk2Exe@main
        with:
          in: .\KeyboardRemap\Vivobook_ASUSLaptop TP412FAC_TP412FA.ahk
#           out: $PWD\Vivobook_ASUSLaptop TP412FAC_TP412FA.exe
          
      - name: Tree output
        run: tree /F

      - name: Get Current date https://stackoverflow.com/a/60942437/12603110 https://stackoverflow.com/a/49766437/12603110
        id: date
        # This is bash for some reason.
        run: |
          $tag = (Get-Date -UFormat '%FT%T.%SZ') -replace '[\?\~\^\:\*\[\]\.\@]','-'
          echo ""date=$tag" >> $GITHUB_OUTPUT"
          
      - name: Releasing...
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
          files: |
            TTS/main.exe
            KeyboardRemap/BaseRemap.exe
            KeyboardRemap/Vivobook_ASUSLaptop TP412FAC_TP412FA.exe
        # env:
          # GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
