name: Building release for AHK scripts

on: push

jobs:
  define-matrix:
    runs-on: windows-latest

    outputs:
      ahk_files: ${{ steps.step_ahk_files.outputs.ahk_files }}

    steps:
      - uses: actions/checkout@v2
      - name: Define file to compile
        id: step_ahk_files
        shell: pwsh
        run: |
          $files = $([string[]](ls **/*.exe.ahk) | ConvertTo-Json -Compress)
          echo $files
          echo "ahk_files=$files" >> $env:GITHUB_OUTPUT
  ahk2exe:
    needs: define-matrix
    strategy: 
      matrix: 
        ahk_file: ${{ fromJSON(needs.define-matrix.outputs.ahk_files) }}
    runs-on: windows-latest
    name: Building AHK
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile AHK
        id: basename
        shell: pwsh
        run: |
          "basename=$((Get-Item '${{matrix.ahk_file}}').BaseName)" >> $env:GITHUB_OUTPUT

      - uses: YoraiLevi/GitHub-Action-Ahk2Exe@main
        with:
            in: '${{ matrix.ahk_file }}'
            out: '${{ steps.basename.outputs.basename}}'
      - shell: pwsh
        run: |
          mkdir .\artifacts\
          cp **/*.exe -Destination .\artifacts\
          tree /F
      - name: Produce Artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'error'
          compression-level: 0 # no compression
          name: '${{ steps.basename.outputs.basename }}'
          path: '.\artifacts\${{ steps.basename.outputs.basename }}'
  release:
    needs:
      - define-matrix
      - ahk2exe
    name: "Create Release"
    runs-on: windows-latest
    steps:
      - name: Tree output
        run: tree /F

      - name: Get Current date https://stackoverflow.com/a/60942437/12603110 https://stackoverflow.com/a/49766437/12603110
        id: date
        run: |
          $tag = (Get-Date -UFormat '%FT%T.%SZ') -replace '[\?\~\^\:\*\[\]\.\@]','-'
          echo "date=$tag" >> $env:GITHUB_OUTPUT
      - uses: actions/download-artifact@v4
      - id: artifact_files
        shell: pwsh
        run: |
          $artifacts = $([string[]](ls $env:GITHUB_WORKSPACE -Recurse -File) | Join-String -Separator "`n")
          echo "artifacts<<EOF" >> $env:GITHUB_OUTPUT
          echo $artifacts >> $env:GITHUB_OUTPUT
          echo "EOF" >> $env:GITHUB_OUTPUT
          echo $artifacts
          tree /F $env:GITHUB_WORKSPACE
      - name: Releasing...
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
          files: ${{steps.artifact_files.outputs.artifacts}}
