name: Building release for AHK scripts

on: push

jobs:
  define-matrix:
    runs-on: windows-latest

    outputs:
      ahk_files: ${{ steps.step_ahk_files.outputs.ahk_files }}

    steps:
      - uses: actions/checkout@v2
      - name: Define file to compile
        id: step_ahk_files
        shell: pwsh
        run: |
          $files = $([string[]](ls **/*.exe.ahk) | ConvertTo-Json -Compress)
          echo $files
          echo "ahk_files=$files" >> "$GITHUB_OUTPUT"
  print:
    needs: define-matrix
    runs-on: windows-latest
    steps:
      - shell: pwsh
        run: |
          echo ${{needs.define-matrix.outputs.ahk_files}}

  ahk2exe:
    needs: define-matrix
    strategy: 
      matrix: 
        ahk_file: ${{ fromJSON(needs.define-matrix.outputs.ahk_files) }}
    runs-on: windows-latest
    name: Building AHK
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile AHK
        id: basename
        shell: pwsh
        run: |
          "basename=$(Get-Item ${{matrix.ahk_file}}).BaseName)" >> "$GITHUB_OUTPUT"

      - uses: YoraiLevi/GitHub-Action-Ahk2Exe@main
        with:
            in: ${{ matrix.ahk_file }}
            out: ${{ steps.basename.outputs}}
      - name: Produce Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.basename.outputs.basename }}
          path: ${{ steps.basename.outputs.basename }}
  release:
    needs:
      - define-matrix
      - ahk2exe
    name: "Create Release"
    runs-on: windows-latest
    steps:
      - name: Tree output
        run: tree /F

      - name: Get Current date https://stackoverflow.com/a/60942437/12603110 https://stackoverflow.com/a/49766437/12603110
        id: date
        # This is bash for some reason.
        run: |
          $tag = (Get-Date -UFormat '%FT%T.%SZ') -replace '[\?\~\^\:\*\[\]\.\@]','-'
          echo "::set-output name=date::$tag"
      - name: Releasing...
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
        # env:
          # GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
